-- 100 Most Expensive Messages
-- Table with top 100 messages with biggest amounts of gas paid for them
-- {"type":"TABLE","name":"100 Most Expensive Messages Table","description":"","options":{"itemsPerPage":25,"columns":[{"numberFormat":"0,0.00","booleanValues":["false","true"],"imageUrlTemplate":"{{ @ }}","imageTitleTemplate":"{{ @ }}","imageWidth":"","imageHeight":"","linkUrlTemplate":"{{ @ }}","linkTextTemplate":"{{ @ }}","linkTitleTemplate":"{{ @ }}","linkOpenInNewTab":true,"name":"gas_fees","type":"float","displayAs":"number","visible":true,"order":0,"title":"Fee Paid","allowSearch":false,"alignContent":"right","allowHTML":true,"highlightLinks":false},{"booleanValues":["false","true"],"imageUrlTemplate":"{{ @ }}","imageTitleTemplate":"{{ @ }}","imageWidth":"","imageHeight":"","linkUrlTemplate":"{{ @ }}","linkTextTemplate":"{{ @ }}","linkTitleTemplate":"{{ @ }}","linkOpenInNewTab":true,"name":"from","type":"string","displayAs":"string","visible":true,"order":1,"title":"From","allowSearch":true,"alignContent":"left","allowHTML":false,"highlightLinks":false},{"booleanValues":["false","true"],"imageUrlTemplate":"{{ @ }}","imageTitleTemplate":"{{ @ }}","imageWidth":"","imageHeight":"","linkUrlTemplate":"{{ @ }}","linkTextTemplate":"{{ @ }}","linkTitleTemplate":"{{ @ }}","linkOpenInNewTab":true,"name":"to","type":"string","displayAs":"string","visible":true,"order":2,"title":"To","allowSearch":false,"alignContent":"left","allowHTML":false,"highlightLinks":false},{"numberFormat":"0,0","booleanValues":["false","true"],"imageUrlTemplate":"{{ @ }}","imageTitleTemplate":"{{ @ }}","imageWidth":"","imageHeight":"","linkUrlTemplate":"{{ @ }}","linkTextTemplate":"{{ @ }}","linkTitleTemplate":"{{ @ }}","linkOpenInNewTab":true,"name":"method","type":"integer","displayAs":"number","visible":true,"order":3,"title":"Method","allowSearch":false,"alignContent":"right","allowHTML":true,"highlightLinks":false},{"booleanValues":["false","true"],"imageUrlTemplate":"{{ @ }}","imageTitleTemplate":"{{ @ }}","imageWidth":"","imageHeight":"","linkUrlTemplate":"{{ @ }}","linkTextTemplate":"{{ @ }}","linkTitleTemplate":"{{ @ }}","linkOpenInNewTab":true,"name":"from_id","type":"string","displayAs":"string","visible":true,"order":4,"title":"from_id","allowSearch":false,"alignContent":"left","allowHTML":false,"highlightLinks":false},{"booleanValues":["false","true"],"imageUrlTemplate":"{{ @ }}","imageTitleTemplate":"{{ @ }}","imageWidth":"","imageHeight":"","linkUrlTemplate":"{{ @ }}","linkTextTemplate":"{{ @ }}","linkTitleTemplate":"{{ @ }}","linkOpenInNewTab":true,"name":"to_type","type":"string","displayAs":"string","visible":true,"order":5,"title":"to_type","allowSearch":false,"alignContent":"left","allowHTML":false,"highlightLinks":false}]},"query_id":9}
--
SELECT least((gas_premium * gas_limit) + (base_fee * gas_used), gas_limit * gas_fee_cap) * 0.000000000000000001 AS gas_fees,
       method,
       method_name
       "from",
       from_id,
       "to",
       to_type
FROM filecoin.messages AS msg
WHERE gas_used > 0
ORDER BY gas_fees DESC
LIMIT 100;