CREATE STREAM {APP_PREFIX}_TIPSETS_TO_REVERT_STREAM (
  "height" STRING,
  "parents" STRING,
  "parent_weight" STRING,
  "parent_state" VARCHAR,
  "blocks" STRING,
  "min_timestamp" BIGINT,
  "state" INT
) WITH (kafka_topic='{APP_PREFIX}_TIPSETS_TO_REVERT_STREAM', value_format='JSON');

CREATE STREAM {APP_PREFIX}_TIPSETS_TO_REVERT_STREAM_AVRO WITH(PARTITIONS=1, VALUE_FORMAT='AVRO', REPLICAS=1) AS SELECT *
FROM {APP_PREFIX}_TIPSETS_TO_REVERT_STREAM EMIT CHANGES;